name: dart_casing
description: Dart library for changing String case style to the desired convention.
version: 1.1.0
author: Florin Bratan <florin@leadcode.dev>
homepage: https://leadcode.dev
repository: https://github.com/bratan/dart_casing

environment:
  sdk: '>=2.12.0 <3.0.0'
